package org.mybatis.generator.model;

import org.gupao.mybatis.study.base.model.BaseEntity;

public class Blog extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.name
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.name
     *
     * @return the value of t_blog.name
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.name
     *
     * @param name the value for t_blog.name
     *
     * @mbggenerated Sun Apr 01 11:35:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}